# Generated by Django 5.2.7 on 2025-10-28 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_uploadedfile_file_content_uploadedfile_file_name_and_more'),
        ('threshold_tuning', '0002_thresholdsuggestion_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='thresholdsuggestion',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='thresholdsuggestion',
            name='reasoning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thresholdsuggestion',
            name='uploaded_file',
            field=models.ForeignKey(blank=True, help_text='Uploaded traffic file used for this suggestion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threshold_suggestions', to='data_management.uploadedfile'),
        ),
    ]
