# Generated by Django 5.2.7 on 2025-10-29 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threshold_tuning', '0003_thresholdsuggestion_confidence_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thresholdsuggestion',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='thresholdsuggestion',
            name='reasoning',
        ),
        migrations.RemoveField(
            model_name='thresholdsuggestion',
            name='uploaded_file',
        ),
    ]
