# Generated by Django 5.2.7 on 2025-10-19 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleAnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('analysis_types', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rules_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_analyses', to='data_management.uploadedfile')),
                ('traffic_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_analyses', to='data_management.uploadedfile')),
            ],
        ),
        migrations.CreateModel(
            name='RuleRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('SHD', 'Shadowing - Rule A shadows Rule B'), ('GEN', 'Generalization - Rule A is more general than Rule B'), ('RXD', 'Redundancy X - Rules trigger on identical patterns'), ('RYD', 'Redundancy Y - Rules are functionally equivalent'), ('COR', 'Correlation - Rules frequently trigger together')], max_length=3)),
                ('rule_a', models.CharField(max_length=50)),
                ('rule_b', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('evidence_count', models.IntegerField(default=0)),
                ('conflicting_fields', models.JSONField()),
                ('description', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='rule_analysis.ruleanalysissession')),
            ],
            options={
                'unique_together': {('session', 'relationship_type', 'rule_a', 'rule_b')},
            },
        ),
    ]
