# Generated by Django 5.2.7 on 2025-11-23 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_name', models.CharField(max_length=255)),
                ('total_rules', models.IntegerField(default=0)),
                ('rarely_used_count', models.IntegerField(default=0)),
                ('redundant_count', models.IntegerField(default=0)),
                ('high_performance_count', models.IntegerField(default=0)),
                ('snapshot_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_optimization_opportunities', models.IntegerField(default=0)),
                ('estimated_ai_improvement', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'performance_snapshots',
            },
        ),
        migrations.CreateModel(
            name='RulePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=50, unique=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('total_requests_processed', models.IntegerField(default=0)),
                ('match_frequency', models.FloatField(default=0.0)),
                ('average_evaluation_time', models.FloatField(default=0.0)),
                ('effectiveness_ratio', models.FloatField(default=0.0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('is_rarely_used', models.BooleanField(default=False)),
                ('is_redundant', models.BooleanField(default=False)),
                ('is_high_performance', models.BooleanField(default=False)),
                ('ai_optimization_suggested', models.BooleanField(default=False)),
                ('ai_optimization_type', models.CharField(blank=True, max_length=50, null=True)),
                ('last_ai_analysis', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rule_performance',
                'indexes': [models.Index(fields=['hit_count'], name='rule_perfor_hit_cou_506700_idx'), models.Index(fields=['is_rarely_used'], name='rule_perfor_is_rare_1756d9_idx'), models.Index(fields=['is_redundant'], name='rule_perfor_is_redu_eea0e6_idx'), models.Index(fields=['ai_optimization_suggested'], name='rule_perfor_ai_opti_b0c1b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='RuleRankingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_rules_order', models.JSONField()),
                ('optimized_rules_order', models.JSONField()),
                ('performance_improvement', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied')], default='proposed', max_length=20)),
                ('ai_generated', models.BooleanField(default=False, help_text='Whether ranking was AI-generated')),
                ('ai_confidence', models.FloatField(default=0.0, help_text='AI confidence in the ranking')),
                ('ai_optimization_rationale', models.JSONField(blank=True, help_text='AI explanation for the ranking', null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rule_ranking_sessions',
            },
        ),
    ]
