# Generated by Django 5.2.7 on 2025-10-19 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RulePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=50, unique=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('average_evaluation_time', models.FloatField(default=0.0)),
                ('false_positive_count', models.IntegerField(default=0)),
                ('effectiveness_ratio', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'rule_performance',
            },
        ),
        migrations.CreateModel(
            name='RuleRankingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_rules_order', models.JSONField()),
                ('optimized_rules_order', models.JSONField()),
                ('performance_improvement', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied')], default='proposed', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rule_ranking_sessions',
            },
        ),
    ]
