# Generated by Django 5.2.7 on 2025-11-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ruleperformance',
            name='rule_perfor_hit_cou_506700_idx',
        ),
        migrations.RemoveIndex(
            model_name='ruleperformance',
            name='rule_perfor_is_rare_1756d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='ruleperformance',
            name='rule_perfor_is_redu_eea0e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='ruleperformance',
            name='rule_perfor_ai_opti_b0c1b4_idx',
        ),
        migrations.AlterField(
            model_name='rulerankingsession',
            name='ai_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rulerankingsession',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rulerankingsession',
            name='ai_optimization_rationale',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
