# Generated by Django 5.2.7 on 2025-10-20 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_analysis', '0002_ruleperformance_rulerankingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_name', models.CharField(max_length=255)),
                ('total_rules', models.IntegerField(default=0)),
                ('rarely_used_count', models.IntegerField(default=0)),
                ('redundant_count', models.IntegerField(default=0)),
                ('high_performance_count', models.IntegerField(default=0)),
                ('average_hit_count', models.FloatField(default=0.0)),
                ('snapshot_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'performance_snapshots',
            },
        ),
        migrations.RemoveField(
            model_name='ruleperformance',
            name='false_positive_count',
        ),
        migrations.AddField(
            model_name='ruleperformance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruleperformance',
            name='is_high_performance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ruleperformance',
            name='is_rarely_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ruleperformance',
            name='is_redundant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ruleperformance',
            name='match_frequency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ruleperformance',
            name='total_requests_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ruleperformance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='ruleperformance',
            index=models.Index(fields=['hit_count'], name='rule_perfor_hit_cou_506700_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleperformance',
            index=models.Index(fields=['is_rarely_used'], name='rule_perfor_is_rare_1756d9_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleperformance',
            index=models.Index(fields=['is_redundant'], name='rule_perfor_is_redu_eea0e6_idx'),
        ),
    ]
