# Generated by Django 5.2.7 on 2025-10-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_analysis', '0004_aioptimizationstrategy_aisuggestion_aiusagelog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
