# Generated by Django 5.2.7 on 2025-10-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule_analysis', '0005_thresholdsuggestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThresholdSuggestion',
        ),
    ]
