# Generated by Django 5.2.7 on 2025-10-30 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0004_remove_uploadedfile_file_and_more'),
        ('rule_analysis', '0006_delete_thresholdsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleanalysissession',
            name='rules_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules_analyses', to='data_management.uploadedfile'),
        ),
        migrations.AlterField(
            model_name='ruleanalysissession',
            name='traffic_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traffic_analyses', to='data_management.uploadedfile'),
        ),
    ]
