# Generated by Django 5.2.7 on 2025-10-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_uploadedfile_file_content_uploadedfile_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_content',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_name',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='filename',
            field=models.CharField(default='unknown_filename.csv', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='supabase_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
