# Generated by Django 5.2.7 on 2025-10-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_1', models.CharField(max_length=255)),
                ('rule_2', models.CharField(max_length=255)),
                ('relationship_type', models.CharField(choices=[('SHD', 'Shadowing'), ('GEN', 'Generalization'), ('RXD', 'Redundancy'), ('COR', 'Correlation')], max_length=10)),
                ('details', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
